from oslo_config import cfg

from ironic.common.i18n import _

opts = [
    cfg.StrOpt('endpoint',
               help=_('URL of the ovh api'),
               default='ovh-eu'),
    cfg.StrOpt('application_key',
               default=None,
               help=_('Application Key, see https://docs.ovh.com/gb/en/customer/first-steps-with-ovh-api/'),
               required=True),
    cfg.StrOpt('consumer_key',
               default=None,
               help=_('Consumer Key, see https://docs.ovh.com/gb/en/customer/first-steps-with-ovh-api/'),
               required=True),
    cfg.StrOpt('application_secret',
               default=None,
               help=_('Application secret, see https://docs.ovh.com/gb/en/customer/first-steps-with-ovh-api/'),
               required=True),
    cfg.IntOpt('poweroff_script_id',
               default=None,
               help=_('Generated by deploy script'),
               required=True),
    cfg.IntOpt('boot_script_id',
               default=None,
               help=_('Generated by deploy script'),
               required=True),
]


def register_opts(conf):
    conf.register_opts(opts, group='ovhapi')
